# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96168e44548728488ed23871e7b830d718a2beefc0a064e7299cb70481bd6bbfcc9eaf53bcc4c308eb393e17aa656d145e68bc6fea8ed75755542ee58a64af5

test:
  secret_key_base: 5cc573d5c9ccd5044b5836e0cb86cd127889396c4b42947c0e0512ef39a7873516c30d840812487c92f5712befdc8fbde57444f24cc9e8b5edb716bfb3e7d21d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
